In [1]:
import numpy as np
import matplotlib.pyplot as plt 
from mpl_toolkits.mplot3d import Axes3D

In [2]:
array = np.array([15,30,45]) 
print(array)

[15 30 45]


In [3]:
array1= np.array([15,30,35,40,50,60,70,80,90,100,110,120,130,140,150])
print(array1.shape)

(15,)


In [4]:
arrayreshape = array1.reshape(5,3) 
print(arrayreshape)

[[ 15  30  35]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]
 [130 140 150]]


In [5]:
print("shape: ",arrayreshape.shape) 
print("dimension: ",arrayreshape.ndim) 
print("data type: ",arrayreshape.dtype.name) 
print("size: ",arrayreshape.size) 
print("type",type(arrayreshape)) 

shape:  (5, 3)
dimension:  2
data type:  int64
size:  15
type <class 'numpy.ndarray'>


In [6]:
array2= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) 
print(array2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
zeros= np.zeros((3,5))
zeros[0,2]=5

print(zeros)

[[0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.empty((3,5))

array([[0., 0., 5., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.arange(10,60,10)

array([10, 20, 30, 40, 50])

In [11]:
x= np.linspace(0,10,50)
print(x)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [12]:
x= np.array([10,20,30])
y= np.array([40,50,60]) 

print(x+y) 
print(x-y) 
print(x**2)

[50 70 90]
[-30 -30 -30]
[100 400 900]


In [13]:
x= np.array([1000,2000,3000,4000,5000,6000,7000])
x

array([1000, 2000, 3000, 4000, 5000, 6000, 7000])

In [14]:
liste = [10,20,30,40]

array = np.array([50,60,70,80])
print(liste)
print(array)

[10, 20, 30, 40]
[50 60 70 80]


In [15]:
array = np.array(liste)
print(array)

[10 20 30 40]


In [16]:
y=x
z=x
y[0]=7 

print(x,y,z)

[   7 2000 3000 4000 5000 6000 7000] [   7 2000 3000 4000 5000 6000 7000] [   7 2000 3000 4000 5000 6000 7000]


In [17]:
a = np.array([1,2,3])
print(a)

d = a.copy()
d

[1 2 3]


array([1, 2, 3])

In [18]:
a= np.array([1000,2000,3000,4000,5000,6000,7000]) 
print(a)

[1000 2000 3000 4000 5000 6000 7000]


In [19]:
print(a[3])

4000


In [20]:
print(a[3:5])

[4000 5000]


In [21]:
reverse_array = a[::-1] 
print(reverse_array)

[7000 6000 5000 4000 3000 2000 1000]


In [22]:
k = np.array([[1,2,3,4,5],[6,7,8,9,10]]) 
print(k)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [23]:
a = array.ravel() 
print(a)

[10 20 30 40]


In [24]:
array_transpose = array2.T
print(array_transpose)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [25]:
array5 = np.array([[10,20],[30,40],[50,60]])
print(array5)

[[10 20]
 [30 40]
 [50 60]]


In [26]:
array5.resize((2,4)) 
print(array5)

[[10 20 30 40]
 [50 60  0  0]]
